"""
GenAI Layer — CriticAgent (Multi-Agent Validation Protocol)

Implements the patent-claimed safety gatekeeper that independently evaluates
every intervention generated by the Generator before it is delivered to the student.
Checks for: pedagogical soundness, demographic bias, and professional tone.
"""
import os
import json
import logging
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

try:
    import google.generativeai as genai
    _API_KEY = os.getenv("GEMINI_API_KEY", "")
    if _API_KEY and _API_KEY != "your_gemini_api_key_here":
        _model = genai.GenerativeModel("gemini-1.5-flash")
        _GENAI_AVAILABLE = True
    else:
        _GENAI_AVAILABLE = False
except ImportError:
    _GENAI_AVAILABLE = False


class CriticAgent:
    """
    Safety gatekeeper for the Generative AI output layer.

    Runs a second independent LLM call to validate the quality, tone, and
    pedagogical soundness of an AI-generated intervention before it reaches
    the student. Corresponds to Patent Claim 3: Multi-Agent Validation Protocol.
    """

    PASS  = "pass"
    FAIL  = "fail"

    def validate(self, intervention: dict, student_context: dict) -> dict:
        """
        Validate an intervention payload.

        Args:
            intervention:     The dict produced by InterventionGenerator.generate()
            student_context:  A dict with keys like risk_score, dropout_type, demographic_group

        Returns:
            {
              "verdict":   "pass" | "fail",
              "reasoning": "One sentence explaining the verdict.",
              "safe_to_deliver": True | False,
              "suggested_revision": "Optional improved wording if verdict is fail."
            }
        """
        if _GENAI_AVAILABLE:
            return self._gemini_validate(intervention, student_context)
        return self._heuristic_validate(intervention, student_context)

    # ── Gemini Validation ────────────────────────────────────────────────────

    def _gemini_validate(self, intervention: dict, student_context: dict) -> dict:
        prompt = f"""
You are a Pedagogical Safety Critic for an AI-powered e-learning intervention system.

A Generator AI has produced the following intervention message for a student:
{json.dumps(intervention, indent=2)}

Student context:
- Risk Score: {student_context.get('risk_score', 'unknown')}
- Dropout Archetype: {student_context.get('dropout_type', 'unknown')}
- Demographic Group: {student_context.get('demographic_group', 'not specified')}

Your task is to critically evaluate this intervention on the following criteria:
1. Pedagogical Soundness — Is the advice educationally valid and evidence-based?
2. Demographic Bias — Does the message treat the student fairly regardless of background?
3. Professional Tone — Is the message compassionate, non-condescending, and motivating?
4. Actionability — Is the remedial task realistic and achievable?

Return ONLY valid JSON with this exact schema:
{{
  "verdict": "pass" or "fail",
  "reasoning": "One concise sentence explaining your verdict.",
  "safe_to_deliver": true or false,
  "suggested_revision": "If verdict is fail, provide a corrected version of the most problematic field. Otherwise empty string."
}}
"""
        try:
            response = _model.generate_content(
                prompt,
                generation_config={"response_mime_type": "application/json"}
            )
            result = json.loads(response.text.strip())
            logger.info(f"Critic verdict: {result.get('verdict')} — {result.get('reasoning')}")
            return result
        except Exception as e:
            logger.error(f"CriticAgent Gemini call failed: {e}")
            return self._heuristic_validate(intervention, student_context)

    # ── Heuristic Fallback ───────────────────────────────────────────────────

    def _heuristic_validate(self, intervention: dict, student_context: dict) -> dict:
        """
        Rule-based fallback that checks minimum quality thresholds.
        Used when the Gemini API is unavailable.
        """
        issues = []

        motivation = intervention.get("motivation", "")
        explanation = intervention.get("explanation", "")
        remedial_task = intervention.get("remedial_task", "")

        # Check for empty critical fields
        if not motivation and not explanation:
            issues.append("Both motivation and explanation are empty.")

        # Check for minimum length
        combined_text = " ".join([motivation, explanation, remedial_task])
        if len(combined_text) < 30:
            issues.append("Intervention message is too short to be meaningful.")

        # Check for potentially harmful phrases
        flagged_phrases = ["you failed", "you are at risk of failing", "you are going to fail"]
        for phrase in flagged_phrases:
            if phrase in combined_text.lower():
                issues.append(f"Contains potentially harmful phrase: '{phrase}'")

        if issues:
            return {
                "verdict": self.FAIL,
                "reasoning": "; ".join(issues),
                "safe_to_deliver": False,
                "suggested_revision": "Please try again with a more supportive and detailed message."
            }

        return {
            "verdict": self.PASS,
            "reasoning": "Heuristic checks passed — message appears complete and benign.",
            "safe_to_deliver": True,
            "suggested_revision": ""
        }
