# Hyperparameters and configuration for OULAD augmentation pipeline

# Preprocessing
START_WEEK = 0
END_WEEK = 40

# Augmentation
DECAY_GRADUAL_TARGET = 0.1
COLLAPSE_THRESHOLD = 5
COLLAPSE_WINDOW = 3

# Hesitation
BASE_HESITATION_SEC = 30.0
DIFFICULTY_INDEX_DEFAULT = 1.5
HESITATION_NOISE_SCALE = 5.0
HESITATION_MIN_SEC = 2.0

# Feature Engineering
BEHAVIORAL_WINDOW = 4

# RL Environment
INTERVENTION_BOOST_EFFECT = 1.5
HESITATION_REDUCTION_EFFECT = 0.8
DROPOUT_PENALTY = -10
RETENTION_REWARD = 1
INTERVENTION_PROB = 0.3
